Repository taljacob2/colman-advanced-web-apps, pull requests merged in 2024-12, with the labels that each got.

#17 Rename `Post.owner` Property To `Post.sender` To Match The Assignment Specification
  controllers/posts_controller.js
  models/posts_model.js
  request.rest
Labels: question, Require

#23 Cover All Informative 400 BadRequest Errors With A Non-Informative Message, For Security Reasons
  controllers/posts_controller.js
Labels: documentation, Require

#20 Rename Entrypoint Of `/posts` To `/post` To Match The Assignment Specification
  app.js
  request.rest
Labels: question, Require

#19 5 update a post
  app.js
  controllers/posts_controller.js
  request.rest
  routes/posts_routes.js
Labels: Require

#25 Initialize Comment Schema And Create Comment
  app.js
  controllers/comments_controller.js
  models/comments_model.js
  request.rest
  routes/comments_routes.js
Labels: Require

#32 Add Get All Comments By Post Id
  controllers/comments_controller.js
  request.rest
  routes/comments_routes.js
Labels: Require

#33 Add Update Comment By Comment Id
  controllers/comments_controller.js
  request.rest
  routes/comments_routes.js
Labels: Require

#34 DELETE comment on a post by the comment ID
  controllers/comments_controller.js
  request.rest
  routes/comments_routes.js
Labels: Require

#39 36 add tests for the whole api so far
  .gitignore
  app.js
  package.json
  server.js
  tests/__tests__/controllers/comments_controller.test.js
  tests/__tests__/controllers/posts_controller.test.js
  tests/jest.config.js
  tests/setup-tests.js
Labels: Require

#41 finish to convert to ts -
  .gitignore
  eslint.config.mjs
  package.json
  src/app.ts
  src/controllers/comments_controller.ts
  src/controllers/posts_controller.ts
  src/models/comments_model.ts
  src/models/posts_model.ts
  src/request.rest
  src/routes/comments_routes.ts
  src/routes/posts_routes.ts
  src/server.ts
  src/tests/comments_controller.test.ts
  src/tests/jest.config.ts
  src/tests/posts_controller.test.ts
  src/tests/setup-tests.ts
  tsconfig.json
Labels: bug, documentation, Require

#44 begining of Auth configuration , adding three test about it . x
  .env.template
  .gitignore
  README.md
  package.json
  src/app.ts
  src/controllers/auth_controller.ts
  src/models/user_model.ts
  src/routes/auth_routes.ts
  src/routes/comments_routes.ts
  src/routes/posts_routes.ts
  src/tests/auth_controller.test.ts
Labels: bug, documentation
