Repository taljacob2/colman-advanced-web-apps, pull requests merged in 2025-01, with the labels that each got.

#49 Fix test after auth
  src/controllers/auth_controller.ts
  src/controllers/comments_controller.ts
  src/controllers/posts_controller.ts
  src/tests/auth_status_codes.test.ts
  src/tests/comments_controller.test.ts
  src/tests/posts_controller.test.ts
Labels: bug, Require

#50 Fix tests database flow
  src/tests/setup-tests.ts
Labels: bug

#52 Add refresh token
  .env.template
  src/controllers/auth_controller.ts
  src/models/user_model.ts
  src/routes/auth_routes.ts
  src/tests/auth_controller.test.ts
  src/tests/auth_status_codes.test.ts
  src/tests/comments_controller.test.ts
  src/tests/posts_controller.test.ts
Labels: bug, documentation

#56 Fix Timeout Test
  src/tests/auth_controller.test.ts
Labels: bug

#54 Add refresh token edit
  src/controllers/auth_controller.ts
  src/tests/auth_controller.test.ts
Labels: documentation

#40 Add Swagger Entrypoint At `/swagger`
  package.json
  src/app.ts
  src/openapi/openapi_loader.ts
  src/openapi/swagger.yaml
Labels: documentation, Require

#57 Feat add test coverage with GitHub pages
  .github/workflows/deploy-coverage-report.yaml
  .github/workflows/run-all-tests.yaml
  .gitignore
  README.md
  babel.config.js
  jest.config.ts
  package.json
  src/tests/jest.config.ts
  src/tests/setup-tests.ts
Labels: documentation, Require

#58 Suggestion For Updating Auth Controller `generateTokens` Method
  .env.template
  .github/workflows/deploy-coverage-report.yaml
  .github/workflows/run-all-tests.yaml
  README.md
  src/controllers/auth_controller.ts
Labels: help wanted, question
